month-8/step1 initial commit - all features
leksey/react-burger pull request #2
Opened 2022-12-08 08:06 UTC by leksey

2022-12-08 09:20 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Вы используйте React Context;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вам нужно поправить семантику в хедере, иконка и текст должны быть обёрнуты в ссылку.

- По макету:

  - Должен скроллится контент (булки должны стоять на месте), в `burger-constructor`: https://yadi.sk/d/6opo4zSvVVKK9A.

  - В хедере должна быть активна первая ссылка: https://yadi.sk/d/kvg17e3QxJ7JJw.

### **Сделает код лучше:**

- Стоит обращать внимание на замечание в терминале, и по возможности их устранять.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-08 09:20 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +}
**Можно лучше:**

Круто что вы реализовали reducer)) Но в будущем (redux), лучше не выносить общую стоимость в глобальный стейт) Оптимальнее всего считать её в самом компоненте, используя `useMemo`.

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/app/app.jsx
>      const dataUrl = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить:**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`
Не забывайте, что константы принято писать в `UPPER_CASE`.

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/app/app.jsx
>          details: {}
**Надо исправить:**

Если значения нет, то нужно использовать `null`, а не пустой объект.

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/app/app.jsx
>          fetch(dataUrl)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше  разместить их в отдельном файле  `utils/burger-api.js`

Например:

```js

const NORMA_API = `https://norma.nomoreparties.space/api`;

export function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(checkResponse )
}

export function sendOrder(data) {
   return fetch(`${NORMA_API}/orders`)
    .then(checkResponse )
}

```

, а не описывать запросы в самом компоненте

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const orderDataUrl = 'https://norma.nomoreparties.space/api/orders'
**Надо исправить:**

Похожее замечание есть в компоненте `App`

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +        let bun = {};
**Надо исправить:**

Используйте null, а не пустой объект.

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
>                          }
**Можно лучше:**

попробуйте использовать тернарные операторы.

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    let filteredData = filterBuns(constructorState.data);
**Можно лучше**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как const

2022-12-08 09:20 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const bodyOrder = `{"ingredients": [${filteredData.map(i => {return `"${i._id}"`})}]}`;
**Надо исправить:**

Не совсем понимаю зачем вам тут такое преобразование. Но используйте для этого JSON.stringify в самой функции запроса, и передавайте просто данные.

```js
 fetch(orderDataUrl, { 
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(bodyOrder)
        })
```

2022-12-09 22:02 UTC, leksey commented on src/components/app/app.jsx
>      const dataUrl = 'https://norma.nomoreparties.space/api/ingredients';
готово
вынес переменную в `src/services/utils.js` (не уверен насчет выбора директории)

2022-12-09 22:04 UTC, leksey commented on src/components/app/app.jsx
>          details: {}
не уверен что понял о чем речь, если о 
`        details: {}`
то исправил

2022-12-09 22:19 UTC, leksey commented on src/components/app/app.jsx
>          fetch(dataUrl)
сделал

2022-12-09 22:19 UTC, leksey commented on src/components/burger-constructor/burger-constructor.jsx
> +    const orderDataUrl = 'https://norma.nomoreparties.space/api/orders'
сделано

2022-12-09 22:22 UTC, leksey commented on src/components/burger-constructor/burger-constructor.jsx
> +        let bun = {};
исправил

2022-12-09 22:23 UTC, leksey commented on src/components/burger-constructor/burger-constructor.jsx
>                          }
пришлось переделать из-за скролла внутри  buns, не актуально

2022-12-09 22:29 UTC, leksey commented on src/components/burger-constructor/burger-constructor.jsx
> +    const bodyOrder = `{"ingredients": [${filteredData.map(i => {return `"${i._id}"`})}]}`;
сделал

2022-12-10 03:22 UTC, ArslanDev666 commented on src/components/app/app.jsx
>          details: {}
Да, всё верно))

2022-12-10 03:24 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята. Удачи в дальнейшем обучении.**

- Все замечания с прошлого ревью были исправлены;

### **Но есть 1 небольшое замечание, которое нужно исправить к следующему этапу:**

- https://yadi.sk/d/chayGlcZG0mUxg. При отправке заказа `/orders`, вам также нужно передавать 2 (одинаковые) булки, **в начало и конец** массива соответственно.

### **Сделает код лучше:**

- Стоит обращать внимание на замечание в терминале, и по возможности их устранять.

2022-12-17 11:47 UTC, merged